// src/stores/transaction/defaultTransactions.ts
import type { Transaction } from './types';

/**
 * Данные транзакций по умолчанию
 * Используются при первой инициализации приложения
 */
export const defaultTransactions: Transaction[] = [
  // ТРАНЗАКЦИИ ПО РЕМОНТУ (RENOVATION)
  {
    id: "renovation_1",
    date: new Date("2025-03-25"),
    amount: -11800,
    currency: "RUB",
    bookCurrency: "USD",
    bookRate: 0.0132,
    bookAmount: -155.76,
    type: "expense",
    description: "Покупка краски",
    categoryId: "renovation",
    sourceEntityId: "cash1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-25"),
    updatedAt: new Date("2025-03-25")
  },
  {
    id: "renovation_2",
    date: new Date("2025-03-24"),
    amount: -131000,
    currency: "IDR",
    bookCurrency: "IDR",
    bookRate: 1,
    bookAmount: -131000,
    type: "expense",
    description: "Плитка для ванной",
    categoryId: "renovation",
    sourceEntityId: "bank2",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-24"),
    updatedAt: new Date("2025-03-24")
  },
  {
    id: "renovation_3",
    date: new Date("2025-03-24"),
    amount: -11000,
    currency: "IDR",
    bookCurrency: "USD",
    bookRate: 0.000069,
    bookAmount: -0.759,
    type: "expense",
    description: "Инструменты",
    categoryId: "renovation",
    sourceEntityId: "bank1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-24"),
    updatedAt: new Date("2025-03-24")
  },
  
  // КОММУНАЛЬНЫЕ ПЛАТЕЖИ (UTILITIES)
  {
    id: "utility_1",
    date: new Date("2025-03-10"),
    amount: -35000,
    currency: "IDR",
    bookCurrency: "IDR",
    bookRate: 1,
    bookAmount: -35000,
    type: "expense",
    description: "Электричество",
    categoryId: "utilities",
    sourceEntityId: "bank1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-10"),
    updatedAt: new Date("2025-03-10")
  },
  {
    id: "utility_2",
    date: new Date("2025-03-12"),
    amount: -28000,
    currency: "IDR",
    bookCurrency: "IDR",
    bookRate: 1,
    bookAmount: -28000,
    type: "expense",
    description: "Водоснабжение",
    categoryId: "utilities",
    sourceEntityId: "bank1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-12"),
    updatedAt: new Date("2025-03-12")
  },
  {
    id: "internet_1",
    date: new Date("2025-03-05"),
    amount: -42000,
    currency: "RUB",
    bookCurrency: "IDR",
    bookRate: 192.05,
    bookAmount: -8066100,
    type: "expense",
    description: "Интернет и ТВ",
    categoryId: "utilities",
    sourceEntityId: "card2",
    sourceEntityType: "account",
    executedByOwnerId: "user_2",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-05")
  },
  
  // ТРАНЗАКЦИИ ПО ЗАРПЛАТЕ (MAIN JOB)
  {
    id: "salary_1",
    date: new Date("2025-03-15"),
    amount: 3500000,
    currency: "IDR",
    bookCurrency: "USD",
    bookRate: 0.000069,
    bookAmount: 241.5,
    type: "income",
    description: "Зарплата за первую половину марта",
    categoryId: "main_job",
    sourceEntityId: "employer",
    sourceEntityType: "external",
    destinationEntityId: "bank1",
    destinationEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-03-15")
  },
  {
    id: "salary_2",
    date: new Date("2025-03-01"),
    amount: 3500000,
    currency: "IDR",
    bookCurrency: "USD",
    bookRate: 0.000069,
    bookAmount: 241.5,
    type: "income",
    description: "Зарплата за вторую половину февраля",
    categoryId: "main_job",
    sourceEntityId: "employer",
    sourceEntityType: "external",
    destinationEntityId: "bank1",
    destinationEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-01")
  },
  
  // ФРИЛАНС
  {
    id: "freelance_1",
    date: new Date("2025-03-08"),
    amount: 850000,
    currency: "RUB",
    bookCurrency: "IDR",
    bookRate: 192.05,
    bookAmount: 163242500,
    type: "income",
    description: "Оплата за дизайн-проект",
    categoryId: "freelance",
    sourceEntityId: "client1",
    sourceEntityType: "external",
    destinationEntityId: "card3",
    destinationEntityType: "account",
    executedByOwnerId: "user_2",
    responsibleOwnerIds: ["user_2"],
    bookId: "wife",
    createdAt: new Date("2025-03-08"),
    updatedAt: new Date("2025-03-08")
  },
  {
    id: "freelance_2",
    date: new Date("2025-03-10"),
    amount: 1500,
    currency: "USD",
    bookCurrency: "USD",
    bookRate: 1,
    bookAmount: 1500,
    type: "income",
    description: "Оплата по международному проекту",
    categoryId: "freelance",
    sourceEntityId: "international_client",
    sourceEntityType: "external",
    destinationEntityId: "dollar",
    destinationEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-10"),
    updatedAt: new Date("2025-03-10")
  },
  
  // ПРОДУКТЫ (GROCERIES)
  {
    id: "groceries_1",
    date: new Date("2025-03-18"),
    amount: -25000,
    currency: "RUB",
    bookCurrency: "IDR",
    bookRate: 192.05,
    bookAmount: -4801250,
    type: "expense",
    description: "Продукты в супермаркете",
    categoryId: "groceries",
    sourceEntityId: "card2",
    sourceEntityType: "account",
    executedByOwnerId: "user_2",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-18"),
    updatedAt: new Date("2025-03-18")
  },
  {
    id: "groceries_2",
    date: new Date("2025-03-22"),
    amount: -32500,
    currency: "RUB",
    bookCurrency: "IDR",
    bookRate: 192.05,
    bookAmount: -6241625,
    type: "expense",
    description: "Покупки на выходные в гипермаркете",
    categoryId: "groceries",
    sourceEntityId: "cash1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-22"),
    updatedAt: new Date("2025-03-22")
  },
  
  // РЕСТОРАНЫ (RESTAURANTS)
  {
    id: "restaurant_1",
    date: new Date("2025-03-16"),
    amount: -18500,
    currency: "IDR",
    bookCurrency: "IDR",
    bookRate: 1,
    bookAmount: -18500,
    type: "expense",
    description: "Ужин в ресторане",
    categoryId: "restaurants",
    sourceEntityId: "card1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-16"),
    updatedAt: new Date("2025-03-16")
  },
  
  // ТРАНСПОРТ (TRANSPORT)
  {
    id: "transport_1",
    date: new Date("2025-03-20"),
    amount: -5000,
    currency: "RUB",
    bookCurrency: "USD",
    bookRate: 0.0132,
    bookAmount: -66,
    type: "expense",
    description: "Автобус в центр города",
    categoryId: "transport",
    sourceEntityId: "cash1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-20"),
    updatedAt: new Date("2025-03-20")
  },
  
  // ЗАПРАВКА (GAS)
  {
    id: "gas_1",
    date: new Date("2025-03-15"),
    amount: -43000,
    currency: "IDR",
    bookCurrency: "IDR",
    bookRate: 1,
    bookAmount: -43000,
    type: "expense",
    description: "Заправка автомобиля",
    categoryId: "gas",
    sourceEntityId: "card1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 70 },
      { ownerId: "user_2", percentage: 30 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-03-15")
  },
  
  // ОБЩЕСТВЕННЫЙ ТРАНСПОРТ (PUBLIC_TRANSPORT)
  {
    id: "public_transport_1",
    date: new Date("2025-03-17"),
    amount: -8500,
    currency: "RUB",
    bookCurrency: "USD",
    bookRate: 0.0132,
    bookAmount: -112.2,
    type: "expense",
    description: "Такси до работы",
    categoryId: "public_transport",
    sourceEntityId: "cash1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-17"),
    updatedAt: new Date("2025-03-17")
  },
  
  // ЗДОРОВЬЕ (HEALTH)
  {
    id: "health_1",
    date: new Date("2025-03-18"),
    amount: -85000,
    currency: "RUB",
    bookCurrency: "IDR",
    bookRate: 192.05,
    bookAmount: -16324250,
    type: "expense",
    description: "Посещение стоматолога",
    categoryId: "health",
    sourceEntityId: "card2",
    sourceEntityType: "account",
    executedByOwnerId: "user_2",
    responsibleOwnerIds: ["user_2"],
    bookId: "wife",
    createdAt: new Date("2025-03-18"),
    updatedAt: new Date("2025-03-18")
  },
  {
    id: "health_2",
    date: new Date("2025-03-22"),
    amount: -32500,
    currency: "RUB",
    bookCurrency: "USD",
    bookRate: 0.0132,
    bookAmount: -429,
    type: "expense",
    description: "Покупка лекарств",
    categoryId: "health",
    sourceEntityId: "cash1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-22"),
    updatedAt: new Date("2025-03-22")
  },
  
  // ОБРАЗОВАНИЕ (EDUCATION)
  {
    id: "education_1",
    date: new Date("2025-03-14"),
    amount: -65000,
    currency: "IDR",
    bookCurrency: "IDR",
    bookRate: 1,
    bookAmount: -65000,
    type: "expense",
    description: "Курсы иностранного языка",
    categoryId: "education",
    sourceEntityId: "bank1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-14"),
    updatedAt: new Date("2025-03-14")
  },
  
  // ПОКУПКИ (SHOPPING)
  {
    id: "shopping_1",
    date: new Date("2025-03-21"),
    amount: -35000,
    currency: "RUB",
    bookCurrency: "IDR",
    bookRate: 192.05,
    bookAmount: -6721750,
    type: "expense",
    description: "Покупка одежды",
    categoryId: "shopping",
    sourceEntityId: "card2",
    sourceEntityType: "account",
    executedByOwnerId: "user_2",
    responsibleOwnerIds: ["user_2"],
    bookId: "wife",
    createdAt: new Date("2025-03-21"),
    updatedAt: new Date("2025-03-21")
  },
  
  // РАЗВЛЕЧЕНИЯ (ENTERTAINMENT)
  {
    id: "entertainment_1",
    date: new Date("2025-03-19"),
    amount: -28000,
    currency: "IDR",
    bookCurrency: "IDR",
    bookRate: 1,
    bookAmount: -28000,
    type: "expense",
    description: "Билеты в кино",
    categoryId: "entertainment",
    sourceEntityId: "card1",
    sourceEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1", "user_2"],
    distributionRules: [
      { ownerId: "user_1", percentage: 50 },
      { ownerId: "user_2", percentage: 50 }
    ],
    bookId: "family",
    createdAt: new Date("2025-03-19"),
    updatedAt: new Date("2025-03-19")
  },
  
  // ИНВЕСТИЦИИ (INVESTMENT)
  {
    id: "investment_1",
    date: new Date("2025-03-25"),
    amount: 120000,
    currency: "IDR",
    bookCurrency: "USD",
    bookRate: 0.000069,
    bookAmount: 8.28,
    type: "income",
    description: "Дивиденды от акций",
    categoryId: "investment",
    sourceEntityId: "stock_market",
    sourceEntityType: "external",
    destinationEntityId: "bank1",
    destinationEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-25"),
    updatedAt: new Date("2025-03-25")
  },
  
  // ПЕРЕВОДЫ МЕЖДУ СЧЕТАМИ
  {
    id: "transfer_1",
    date: new Date("2025-03-14"),
    amount: -1000000,
    currency: "IDR",
    bookCurrency: "USD",
    bookRate: 0.000069,
    bookAmount: -69,
    type: "transfer",
    description: "Перевод на карту для ежедневных расходов",
    sourceEntityId: "bank1",
    sourceEntityType: "account",
    destinationEntityId: "card1",
    destinationEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-14"),
    updatedAt: new Date("2025-03-14")
  },
  {
    id: "transfer_2",
    date: new Date("2025-03-14"),
    amount: 1000000,
    currency: "IDR",
    bookCurrency: "USD",
    bookRate: 0.000069,
    bookAmount: 69,
    type: "transfer",
    description: "Перевод с основного счета",
    sourceEntityId: "bank1",
    sourceEntityType: "account",
    destinationEntityId: "card1",
    destinationEntityType: "account",
    executedByOwnerId: "user_1",
    responsibleOwnerIds: ["user_1"],
    bookId: "my",
    createdAt: new Date("2025-03-14"),
    updatedAt: new Date("2025-03-14")
  }
];